---
- hosts: web1
  become: yes
  become_method: sudo
  tasks:
  - name: Ensure java Runtime Environment is installed
    apt:
      name: default-jre
      state: present
      update_cache: yes
  - name: Download Hazelcast
      get_url:
          url: https://repo1.maven.org/maven2/com/hazelcast/hazelcast/5.0.2/hazelcast-5.0.2.jar
          dest: /var/hazelcast/hazelcast.jar
          mode: a+r
  - name: Copy Hazelcast starting script
    copy:
      src: hazelcast.sh
      dest: /var/hazelcast/hazelcast.sh
      mode: a+x
  - name: Configure Hazelcast as a service
    file: 
      path: /etc/init.d/hazelcast
      state: link
      force: yes
      src: /var/hazelcast/hazelcast.sh
  - name: Start Hazelcast
    service:
      name: hazelcast
      enabled: yes
      state: started
